### ISSUE TITLE
Error while instantiating a Msbuddy object

### ISSUE THREAD

**Issue by josiehong** [Philipbear/msbuddy#1]
I am trying to run MSBUDDY for formula prediction on my own MS/MS data. I installed python 3.10 and msbuddy 0.2.9, and used the following codes: 

```python
from msbuddy import Msbuddy, MsbuddyConfig

# instantiate a MsbuddyConfig object
msb_config = MsbuddyConfig(ms_instr='qtof', # supported: "qtof", "orbitrap", "fticr" or None
                                                # custom MS1 and MS2 tolerance will be used if None
                           ppm=True,  # use ppm for mass tolerance
                           ms1_tol=5,  # MS1 tolerance in ppm or Da
                           ms2_tol=10,  # MS2 tolerance in ppm or Da
                           halogen=False)

# instantiate a Msbuddy object
msb_engine = Msbuddy(msb_config)
```

However, the following error showed up while instantiating a Msbuddy object: 

```bash
msbuddy: molecular formula annotation for MS-based small molecule analysis.
Developed and maintained by Shipei Xing.
Traceback (most recent call last):
  File "/data/<user name>/FIDDLE/run_buddy/run_buddy.py", line 12, in <module>
    msb_engine = Msbuddy(msb_config)
  File "/home/<user name>/miniconda3/envs/buddy/lib/python3.9/site-packages/msbuddy/main.py", line 206, in __init__
    shared_data_dict = init_db()  # database initialization
  File "/home/<user name>/miniconda3/envs/buddy/lib/python3.9/site-packages/msbuddy/load.py", line 63, in init_db
    check_download_joblibload(
  File "/home/<user name>/miniconda3/envs/buddy/lib/python3.9/site-packages/msbuddy/load.py", line 41, in check_download_joblibload
    download(url, str(path))
  File "/home/<user name>/miniconda3/envs/buddy/lib/python3.9/site-packages/gdown/download.py", line 259, in download
    filename_from_url = m.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
```

I am quite confused about that. Could you please give me an idea of how to solve that?

**Comment by Philipbear** [comment]
Hi,

I’m aware of this issue. Please allow me ~1 week to fix this. Meanwhile, a newly updated model will be released in the next version. Thanks for raising this.

**Comment by Philipbear** [comment]
Hi,

msbuddy version 0.3.0 has just been released. You have to install lightgbm package to use msbuddy.

The error you raised is related to the database download -  now all the data have been moved to GitHub release, and it should be solved now.

Thank you for using msbuddy.
